Dev 1992 approval job
campsi/admin pull request #39
Opened 2022-10-11 15:52 UTC by Achalhii

In this feature, we allow front users to be able to interact with a job waiting for approval.

What was done :

1.  Add two data in the api client : `clientEmail` `clientId` which comes from the connected client

2. Be able to give its approval, with a preview of the future result : 
<img width="1122" alt="Capture d’écran 2022-10-11 à 17 27 41" src="https://user-images.githubusercontent.com/60391768/195134540-74272c10-745e-46e4-9979-9480227e4b5e.png">

3. Have an approval history

<img width="1280" alt="Capture d’écran 2022-10-11 à 17 48 48" src="https://user-images.githubusercontent.com/60391768/195139481-4d443875-daab-44ba-8557-d942b28251d6.png">

++ Errors generated by the automator are correctly displayed and managed by the front
++ Tested locale, can go into production without disturbing the function of existing jobs

2022-10-11 16:02 UTC, Achalhii commented on src/components/AutomatorService/AutomatorJob.js
> +      job.actions?.[action]?.approval.approved === undefined
`job.actions.[action].approval.approved` can be equal false/true/undefined

2022-10-12 07:11 UTC, rombat requested changes

2022-10-12 07:11 UTC, rombat commented on src/Api.js
> +    this.client.get(`/auth/me`).then((response) => {
You should avoid code duplication here, it's exactly the same as the one on line 53

2022-10-12 07:11 UTC, rombat commented on src/components/AutomatorService/AutomatorJob.js
> +                : "Disproves"
"Disproves" => "Disapproved"

2022-10-12 07:11 UTC, rombat commented on src/components/AutomatorService/AutomatorJob.js
> +  disprovesAction(job, action) {
I think you could do a single function for approving/disapproving. It seems to me that the only differences are `approved` and `status` values, the rest is code duplication

2022-10-14 08:23 UTC, rombat approved these changes

2022-10-21 08:39 UTC, merged