Dev 3351 feat/approval docs
campsi/admin pull request #65
Opened 2023-05-09 07:43 UTC by Achalhii

2023-05-09 07:48 UTC, Achalhii commented on src/components/AutomatorService/AutomatorService.js
> +              {job.params?.origin === "caas-styleguide" && (
```suggestion
              {job.params?.origin === 'caas-styleguide' && (
```

2023-05-09 09:59 UTC, Fluorz requested changes

2023-05-09 09:59 UTC, Fluorz commented on src/components/DocsService/ResourceForm.js
> +function getActions(service, resourceName) {
tu peux utiliser des ternaires à la place de faire des arrays à render

2023-05-09 10:38 UTC, gabila-r commented
What is this git history ? 😨

2023-05-09 15:30 UTC, Achalhii commented
> What is this git history ? 😨

FF...

2023-05-09 16:04 UTC, Achalhii commented on src/components/DocsService/ResourceForm.js
> +function getActions(service, resourceName) {
L'array n'est pas envoyé à un render mais au params d'un component react https://ant.design/components/card#:~:text=of%20the%20Card-,Array%3CReactNode%3E,-%2D

2023-05-11 12:58 UTC, Fluorz approved these changes

2023-05-11 12:59 UTC, Fluorz commented on src/components/DocsService/ResourceForm.js
> +function getActions(service, resourceName) {
https://stackoverflow.com/a/47771259

2023-05-15 08:06 UTC, merged